CMS02/ViewModels/CommentsViewModel.cs
using System;
using CMS02_Models.Models;

namespace CMS02.ViewModels
{
    public class CommentsViewModel
    {
        public int CommentId { get; set; }

        public string CommentText { get; set; }

        public int UpdateId { get; set; }

        public string UserId { get; set; }

        public DateTime CommentDate { get; set; }

        public ApplicationUser User { get; set; }
    }
}

CMS02/ViewModels/GoalViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using CMS02_Models.Models;

namespace CMS02.ViewModels
{
    public class GoalViewModel
    {
        public int GoalId { get; set; }

        public string GoalName { set; get; }

        public string Desc { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTime StartDate { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTime EndDate { get; set; }

        public double? Target { get; set; }

        public bool GoalType { get; set; }

        public int MetricId { get; set; }

        public int GoalStatusId { get; set; }

        public string UserId { get; set; }

        public Metric Metric { get; set; }

        public IEnumerable<SelectListItem> GoalStatuses { get; set; }

        public GoalStatus GoalStatus { get; set; }

        public ApplicationUser User { get; set; }

        public DateTime CreatedDate { get; set; }

        public bool? Supported { get; set; }

      //  public int? GroupGoalId { get; set; }

        public int? GroupId { get; set; }

        public virtual IEnumerable<Support> Supports { get; set; }

        public virtual IEnumerable<Update> Updates { get; set; }

    }
}

CMS02/ViewModels/UpdateViewModel.cs
using System;
using System.Collections.Generic;
using CMS02_Models.Models;

namespace CMS02.ViewModels
{
    public class UpdateViewModel
    {
        public int UpdateId { get; set; }

        public string Updatemsg { get; set; }

        public double? Status { get; set; }

        public int GoalId { get; set; }

        public DateTime UpdateDate { get; set; }

        public virtual Goal Goal { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }

        public bool? IsSupported { get; set; }

        public virtual ICollection<UpdateSupport> UpdateSupports { get; set; }
    }
}

CMS02/Controllers/GoalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using CMS02.Mailers;
using CMS02.Properties;
using CMS02.ViewModels;
using CMS02_BusinessLogic;
using CMS02_BusinessLogic.Extensions;
using CMS02_Models.Models;
using Microsoft.AspNet.Identity;

namespace CMS02.Controllers
{
    [Authorize]
    public class GoalController : Controller
    {
        private readonly IGoalBusiness _goalBusiness;
        private readonly IMetricBusiness _metricBusiness;
        private readonly IFocusBusiness _focusBusiness;
        private readonly ISupportBusiness _supportBusiness;
        private readonly IUpdateBusiness _updateBusiness;
        private readonly ICommentBusiness _commentBusiness;
        private readonly IUserBusiness _userBusiness;
        public readonly ISecurityTokenBusiness SecurityTokenBusiness;
        public readonly ISupportInvitationBusiness SupportInvitationBusiness;
        private readonly IGoalStatusBusiness _goalStatusBusiness;
        private readonly ICommentUserBusiness _commentUserBusiness;
        private readonly IUpdateSupportBusiness _updateSupportBusiness;

        private IUserMailer _userMailer = new UserMailer();
        public IUserMailer UserMailer
        {
            get { return _userMailer; }
            set { _userMailer = value; }
        }

        public GoalController(IGoalBusiness goalBusiness, IMetricBusiness metricBusiness, IFocusBusiness focusBusiness, ISupportBusiness supportBusiness, IUpdateBusiness updateBusiness, ICommentBusiness commentBusiness, IUserBusiness userBusiness, ISecurityTokenBusiness securityTokenBusiness, ISupportInvitationBusiness supportInvitationBusiness, IGoalStatusBusiness goalStatusBusiness, ICommentUserBusiness commentUserBusiness, IUpdateSupportBusiness updateSupportBusiness)
        {
            _goalBusiness = goalBusiness;
            SupportInvitationBusiness = supportInvitationBusiness;
            _metricBusiness = metricBusiness;
            _focusBusiness = focusBusiness;
            _supportBusiness = supportBusiness;
            _updateBusiness = updateBusiness;
            _commentBusiness = commentBusiness;
            _userBusiness = userBusiness;
            SecurityTokenBusiness = securityTokenBusiness;
            _goalStatusBusiness = goalStatusBusiness;
            _commentUserBusiness = commentUserBusiness;
            _updateSupportBusiness = updateSupportBusiness;
        }

        public ActionResult Index(int id)
        {
            var goal = _goalBusiness.GetGoal(id);
            if (goal == null)
            {
                return HttpNotFound();
            }
            var goalDetails = Mapper.Map<Goal, GoalViewModel>(goal);
            goalDetails.Supported = _supportBusiness.IsGoalSupported(id, User.Identity.GetUserId());
            var goalstatus = _goalStatusBusiness.GetGoalStatus();
            goalDetails.GoalStatuses = goalstatus.ToSelectListItems(goal.GoalStatusId);
            return View(goalDetails);
        }

        public ViewResult MyGoal()
        {
            string userid = User.Identity.GetUserId();
            var goals = _goalBusiness.GetMyGoals(userid);
            var goalDetails = Mapper.Map<IEnumerable<Goal>, IEnumerable<GoalViewModel>>(goals);
            return View(goalDetails);
        }

        public ViewResult FollowedGoal()
        {
            var followed = _supportBusiness.GetUserSupportedGoals(User.Identity.GetUserId(), _goalBusiness);
            return View(followed);
        }

        public PartialViewResult Create()
        {
            var createGoal = new GoalFormModel();
            var metrics = _metricBusiness.GetMetrics();
            var goalstatus = _goalStatusBusiness.GetGoalStatus();
            createGoal.Metrics = metrics.ToSelectListItems(-1);
            return PartialView(createGoal);
        }

        [HttpPost]
        public ActionResult Create(GoalFormModel createGoal)
        {
            Goal goal = Mapper.Map<GoalFormModel, Goal>(createGoal);
            var errors = _goalBusiness.CanAddGoal(goal, _updateBusiness).ToList();
            ModelState.AddModelErrors(errors);
            if (ModelState.IsValid)
            {
                _goalBusiness.CreateGoal(goal);
                return RedirectToAction("Index", new { id = goal.GoalId });
            }
            var metrics = _metricBusiness.GetMetrics();
            var goalstatuss = _goalStatusBusiness.GetGoalStatus();
            createGoal.Metrics = metrics.ToSelectListItems(-1);
            return View("Create", createGoal);
        }

        public ActionResult Edit(int id)
        {
            var goal = _goalBusiness.GetGoal(id);
            GoalFormModel editGoal = Mapper.Map<Goal, GoalFormModel>(goal);
            if (goal == null)
            {
                return HttpNotFound();
            }
            var metrics = _metricBusiness.GetMetrics();
            if (goal.Metric != null)
                editGoal.Metrics = metrics.ToSelectListItems(goal.Metric.MetricId);
            else
                editGoal.Metrics = metrics.ToSelectListItems(-1);
            return View(editGoal);
        }

        [HttpPost]
        public ActionResult Edit(GoalFormModel editGoal)
        {
            Goal goalToEdit = Mapper.Map<GoalFormModel, Goal>(editGoal);
            var errors = _goalBusiness.CanAddGoal(goalToEdit, _updateBusiness);
            ModelState.AddModelErrors(errors);
            if (ModelState.IsValid)
            {
                _goalBusiness.EditGoal(goalToEdit);
                return RedirectToAction("Index", new { id = editGoal.GoalId });
            }
            else
            {
                var metrics = _metricBusiness.GetMetrics();
                var goalstatus = _goalStatusBusiness.GetGoalStatus();
                var goal = _goalBusiness.GetGoal(editGoal.GoalId);
                if (goal.Metric != null)
                    editGoal.Metrics = metrics.ToSelectListItems(goal.Metric.MetricId);
                else
                    editGoal.Metrics = metrics.ToSelectListItems(-1);

                return View(editGoal);
            }
        }

        [HttpPost]
        public string GoalStatus(int id, int goalid)
        {
            var goal = _goalBusiness.GetGoal(goalid);
            goal.GoalStatusId = id;
            _goalBusiness.SaveGoal();
            string msg = goal.GoalStatus.GoalStatusType;
            return msg;
        }

        public ActionResult Delete(int id)
        {
            var goal = _goalBusiness.GetGoal(id);
            if (goal == null)
            {
                return HttpNotFound();
            }
            return View(goal);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var goal = _goalBusiness.GetGoal(id);
            if (goal == null)
            {
                return HttpNotFound();
            }

            _goalBusiness.DeleteGoal(id);
            return RedirectToAction("Index", "Home");
        }

        public PartialViewResult MyGoals()
        {
            string userid = User.Identity.GetUserId();
            var goals = _goalBusiness.GetMyGoals(userid);
            return PartialView("_MyGoalsView", goals);
        }

        public PartialViewResult GoalsFollowing()
        {
            var followed = _supportBusiness.GetUserSupportedGoals(User.Identity.GetUserId(), _goalBusiness);
            return PartialView("_FollowedGoals", followed);
        }

        public PartialViewResult DisplayUpdates(int id)
        {
            var Updates = Mapper.Map<IEnumerable<Update>, IEnumerable<UpdateViewModel>>(_updateBusiness.GetUpdatesByGoal(id));
            foreach (var item in Updates)
            {
                item.IsSupported = _updateSupportBusiness.IsUpdateSupported(item.UpdateId, User.Identity.GetUserId());
            }
            UpdateListViewModel updates = new UpdateListViewModel()
            {

                Updates = Updates,
                Metric = _goalBusiness.GetGoal(id).Metric,
                Target = _goalBusiness.GetGoal(id).Target,
                // IsSupported =  _updateSupportBusiness.IsUpdateSupported(,((SocialGoalUser)(User.Identity)).UserId)
            };
            return PartialView("_UpdateView", updates);
        }

        public ViewResult Supporters(int id)
        {
            var members = _supportBusiness.GetSupportersOfGoal(id, _userBusiness);
            GoalSupporterViewModel gsvm = new GoalSupporterViewModel() { GoalId = id, Goal = _goalBusiness.GetGoal(id), Users = members };
            return View(gsvm);
        }

        [HttpPost]
        public ActionResult SaveUpdate(UpdateFormModel newupdate)
        {
            // Update update = Mapper.Map<UpdateFormModel, Update>(newupdate);
            if (ModelState.IsValid)
            {
                Update update = Mapper.Map<UpdateFormModel, Update>(newupdate);
                update.Goal = _goalBusiness.GetGoal(newupdate.GoalId);
                var updateVal = _updateBusiness.GetHighestUpdateValue(newupdate.GoalId);
               
                if(updateVal!=null)
                {  
                    if (updateVal.Status <= newupdate.Status)
                    {
                        _updateBusiness.CreateUpdate(update);
                       
                    }
                    else
                    {
                        update.Status = -1;
                        ModelState.AddModelError(update.Updatemsg, "cannot enter");
                    }
                }
                else
                {
                    _updateBusiness.CreateUpdate(update);
                }


                     var Updates = Mapper.Map<IEnumerable<Update>, IEnumerable<UpdateViewModel>>(_updateBusiness.GetUpdatesByGoal(newupdate.GoalId));
                     foreach (var item in Updates)
                     {

CMS02/Views/Goal/Create.cshtml
@using Microsoft.AspNet.Identity
@model GoalFormModel
@{
    ViewBag.Title = "Home Page";
        //Layout = "~/Views/Shared/_HomeLayout.cshtml";

}
<div>
    <div class="span5">
        @using (Html.BeginForm("Create", "Goal", FormMethod.Post, new { @id = "form" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <fieldset>
                <legend></legend>
                <table>
                    <tr>

                        <td>
                            @Html.TextBoxFor(model => model.GoalName, new { @class = "span3", style = "display:block;width:270px;;float:left", placeholder = "Enter the event name" })<br>
                            @Html.ValidationMessageFor(model => model.GoalName)
                        </td>
                    </tr>
                    <tr>

                        <td class="editor-field">
                            @Html.TextAreaFor(model => model.Desc, new { @class = "span3", placeholder = "Enter the description", style = "display:block;width:270px;;float:left" })
                            @Html.ValidationMessageFor(model => model.Desc)
                        </td>
                    </tr>
                    <tr>

                        <td>
                            @Html.TextBoxFor(model => model.StartDate, new { @class = "ui-datepicker span3", @style = "display:block;width:270px;;float:left", placeholder = "Enter the start date", @readonly = "readonly" })
                            @Html.ValidationMessageFor(model => model.StartDate)
                        </td>
                    </tr>
                    <tr>

                        <td>
                            @Html.TextBoxFor(model => model.EndDate, new { @class = "ui-datepicker span3", @style = "display:block;width:270px;;float:left", placeholder = "Enter the end date", @readonly = "readonly" })
                            @Html.ValidationMessageFor(model => model.EndDate)
                        </td>
                    </tr>
                    <tr>

                        <td>

                            @Html.DropDownListFor(model => model.MetricId, Model.Metrics, "--Select Metric--", new { @class = "span4", @style = "display:block;width:270px;;float:left" })
                            @Html.ValidationMessageFor(model => model.MetricId)
                        </td>
                    </tr>
                    <tr>

                        <td>
                            @Html.TextBoxFor(model => model.Target, new { @class = "span3", id = "Target", placeholder = "Enter the target to be achieved", style = "width: 270px;" })
                            <a href="#" id="targetinfo" rel="popover" data-content="Fix the target of the event based on metric selected" data-trigger="hover" data-placement="top" data-originals-title="Target"><i class="icon-info-sign"></i> </a>
                            <div id="NumberValidation"></div>
                        </td>
                    </tr>
                    <tr>
                        <td>@Html.CheckBoxFor(model => model.GoalType, true)&nbsp;&nbsp;Make this event as private</td>
                    </tr>
                    <tr><td height="20"></td></tr>
                    <tr>
                        <td>
                            <button id="submitbtn" class="btn btn-primary" value="Submit"> Create</button>&nbsp;&nbsp;
                            <button class="btn" type="reset" value="Cancel" onclick="window.location.href='@Url.Action("Index", "Home")'">Cancel</button>
                        </td>
                    </tr>

                    @Html.Hidden("UserId", User.Identity.GetUserId())

                </table>

            </fieldset>
        }
    </div>
</div>
<script type="text/javascript">


    $(document).ready(function () {

        $('.ui-datepicker').each(function (i, v) {
            $(v).datepicker({
                dateFormat: 'dd-M-yy',
                buttonImage: '@Url.Content("~/Content/calendar.gif")',
                buttonImageOnly: true,
                showOn: "button"
            });

        });

        $('#form').submit(function (e) {
            var target = $('#Target').val();
            if (target != '') {
                if (DecimalValidate(target)) {
                    $('#NumberValidation').html('');
                    return true;
                }
                else {
                    $('#NumberValidation').html('<label class="field-validation-error">Please enter valid status</label>');
                    e.preventDefault();
                    return false;
                }
            }

        });

    });

    $("#Description").focus(function () {
        $(this).animate({ "height": "60px" }, "slow");
        return false;
    });
    $("#Description").blur(function () {
        $("#Description").animate({ "height": "22px" }, "slow");
        return false;
    });

    $(function () {
        $("#targetinfo").popover();
    });


    function DecimalValidate(num) {
        var regex = /^[-+]?[0-9]+(\.[0-9]+)?$/;
        if (regex.test(num)) {
            return true;
        } else {
            return false;
        }
    }


</script>

CMS02/Views/Goal/Edit.cshtml
@using Microsoft.AspNet.Identity
@model GoalFormModel
@{
    ViewBag.Title = "Edit Event";
   }
<div class="span12 well">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)

        <fieldset>
            <h4>Edit @Html.DisplayFor(model => model.GoalName)</h4>
            @Html.HiddenFor(model => model.GoalId)
            <table class="table">
                <tr>
                    <td>
                        @Html.LabelFor(model => model.GoalName, "Event Name")
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.GoalName, new { @class = "span11" })
                        @Html.ValidationMessageFor(model => model.GoalName)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.Desc, "Description")
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.Desc, new { @class = "span11" })
                        @Html.ValidationMessageFor(model => model.Desc)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.StartDate, "Start Date")
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.StartDate, String.Format("{0:dd-MMM-yyyy}", Model.StartDate), new { @class = "ui-datepicker span11", @readonly = "readonly" })
                        @Html.ValidationMessageFor(model => model.StartDate)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.EndDate, "End Date")
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.EndDate, String.Format("{0:dd-MMM-yyyy}", Model.EndDate), new { @class = "ui-datepicker span11", @readonly = "readonly" })
                        @Html.ValidationMessageFor(model => model.EndDate)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.MetricId, "Metric")
                    </td>
                    <td>
                        @Html.DropDownListFor(model => model.MetricId, Model.Metrics, "--Select--", new { @class = "span11" })
                        @Html.ValidationMessageFor(model => model.MetricId)
                    </td>
                </tr>

                <tr>
                    <td>
                        @Html.LabelFor(model => model.Target, "Target")
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.Target, new { @class = "span11" })
                        @Html.ValidationMessageFor(model => model.Target)
                    </td>
                    <td>
                        @Html.Hidden("UserId", User.Identity.GetUserId())
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.CheckBoxFor(model => model.GoalType, true)
                </td>
                <td>
                    @Html.Label("Make this Event Private")
            </td>
        </tr>
    </table>
    <button class="btn btn-primary" type="submit" value="Save" onclick="editSave(@Model.GoalId)">
        Save
    </button>
    <button class="btn" type="reset" value="Cancel" onclick="window.location.href='@Url.Action("Index", "Goal", new {id =@Model.GoalId })'">
        Cancel
    </button>
</fieldset>

        <div id="divEdit@(Model.GoalId)">
        </div>
    }
</div>
<script type="text/javascript">
    //    $(document).ready(function () {
    //
    //        $('.ui-datepicker').each(function (i, v) {
    //            $(v).val($.datepicker.formatDate('dd-M-yy', new Date($(v).val())))
    //            $(v).datepicker({
    //                dateFormat: 'dd-M-yy',
    //                buttonImage: 'Url.Content("~/Content/calendar.gif")',
    //                buttonImageOnly: true,
    //                showOn: "button"
    //            });
    //        });
    //    });


    $(document).ready(function () {
        $('.ui-datepicker').each(function (i, v) {

            $(".ui - datepicker").val(" ");
            //$(v).val($.datepicker.formatDate('dd-M-yy', new Date($(v).val())));
            $(v).datepicker({
                dateFormat: 'dd-M-yy',
                buttonImage: '@Url.Content("~/Content/calendar.gif")',
                buttonImageOnly: true,
                showOn: "button"
            });
        });
    });

</script>

CMS02/Views/Goal/InviteUser.cshtml
@model CMS02_Models.Models.ApplicationUser
<div class="alert"> @Model.UserName has been invited to follow the event.</div>

CMS02/Views/Goal/ListOfGoals.cshtml
@model GoalsPageViewModel
@{
    ViewBag.Title = "ListOfGoals";
}
@*<script src="/Scripts/handlebars-1.0.rc.1.js" type="text/javascript"></script>*@
<div class="well span12">
    <div class="span4" style="padding-left:30px;"><h4>Events</h4></div>
    <div class="span8">
        <strong>Sort By</strong>
        @Html.DropDownList("sortby", Model.SortBy, new { @onchange = "ListOfGoals();" })
        <strong>Filter By</strong>
        @Html.DropDownList("filterby", Model.FilterBy, new { @onchange = "ListOfGoals();" })
    </div>
    <div id="listofgoals" style="float:left;" class="span11">

        @if (Model.GoalList.Count() == 0)
        {
            <div class="alert alert-info">
                No results found
            </div>
        }
        else
        {
            <div class="span12" id="goalListContainer" style="margin-top:10px;">
                <hr />
                <table class="table">
                    @Html.Partial("_Goalslist", Model.GoalList)
                </table>
            </div>
            if (Model.GoalList.Count() == 5)
            {
                <div id="morelink"> <a href="#" onclick="loadMore();">More Events</a></div>
            }
        }
    </div>
</div>
<div id="content" style="color:Red;"></div>
<div class="hiddenData" style="display:none;"></div>
<script type="text/javascript">

    $(document).ready(function () {

        //to load templates to a hidden div
        $.get('/Templates/Templates.htm', function (data) {
            $('.hiddenData').html(data);
        });
    });

    $(window).scroll(function () {
        if ($(window).scrollTop() == $(document).height() - $(window).height()) {
            loadMore();
        }
    });
    var current = 0;
    var currentGoalPage = 0;
    function loadMore() {
        var sortBy = $('#sortby').val();
        var filterBy = $('#filterby').val();


        if (currentGoalPage > -1) {
            currentGoalPage++;

            $.ajax({
                url: "/Goal/GoalList",
                type: "POST",
                data: { sortBy: sortBy, filterBy: filterBy, page: currentGoalPage },
                dataType: "json",
                beforeSend: function () {
                    console.log("a");
                    $("#goalListContainer").find(".alert-info").remove();
                    $("#goalListContainer").append('<div class="alert alert-info" id="loadimage">Loading...</div>');
                },
                success: function (data) {
                    $('#loadimage').remove();
                    if (data.length != 0) {
                        loadTemplate(data);
                        $('#morelink').show();
                        if (data.length < 5) {
                            addNoMoreGoals();
                        }
                    } else {
                        addNoMoreGoals();
                    }
                }
            });

        }

        function addNoMoreGoals() {
            $('#morelink').hide();
            currentGoalPage = -1;
            $("#goalListContainer").find(".alert-info").remove();
            $("#goalListContainer").append('<div class="alert alert-info"> No more events found </div>');
        }
    }

    function loadTemplate(data) {
        var source = $("#goalList-template").html();

        var template = Handlebars.compile(source);
        $("#goalListContainer").append(template({ objects: data }));
    }

    function ListOfGoals() {
        var sortby = $("#sortby").val();
        var filterby = $("#filterby").val();
        var url = '/Goal/GoalList';
        $.get(url, { 'sortBy': sortby, 'filterBy': filterby, 'page': 0 }, function (result) {
            $("#goalListContainer").html('');
            if (result == '') {
                $("#goalListContainer").append('<div class="alert alert-info"> No events found </div>');
                $('#morelink').hide();
            }
            else {
                $('#morelink').show();
            }
            currentGoalPage = 0;
            loadTemplate(result);

        });

        //document.location.href="/Goal/GoalList?sortBy="+sortby+"&filterBy="+filterby;

    }
</script>

CMS02/Views/Goal/MyGoal.cshtml
@model IEnumerable<GoalViewModel>
@{
    ViewBag.Title = "MyGoal";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}
@if (Model.Count() == 0)
{
    <div class="alert alert-info">
        No results To Display
    </div>
}
@foreach (var item in Model)
{
    <div class="span2 alert goals">
        <div>
            @Html.ActionLink(@item.GoalName + " - " + @item.Supports.Count() + " Support(s)", "Index", "Goal", new { id = @item.GoalId }, null)
        </div>

    </div>
}

CMS02/Views/Goal/Reportpage.cshtml
@{
    ViewBag.Title = "Reportpage";
}

<div id="goalReport" class="well" style="padding-bottom:40px;">
</div>


<script type="text/javascript">
   
    $(document).ready(function () {
        LoadReport();
    });
   

    function LoadReport() {
        var goalId = $('#GoalId').val();
        var updates = $('#Updates').val();

        $.get("/Goal/GetGoalReport", { id: goalId }, function (result) {

            var data = [], target = [];
            $(result.Data).each(function (i, v) {
                data.push([v.Date, v.Value]);
            });
            $(result.Target).each(function (i, v) {
                target.push([v.EndDate, v.Target]);
            });
            if (data.length > 0) {
                setTimeout(drawChart(data, target), 10000);
            }

            if (data.length == 0) {
                $('#goalldetail').removeClass('well');
            }
            else {
                $('#goalldetail').addClass('well');
            }
        });
    }
</script>

CMS02/Views/Goal/Supporters.cshtml
@{
    ViewBag.Title = "Supporters";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}
@model GoalSupporterViewModel
<div class="span10 well">
    <h4>
        Supporters
    </h4>
    <div class="span8">
        @foreach (var item in Model.Users)
        {
            <div>
                <div style="position: relative">
                    <div>
                        <a href="@Url.Action("UserProfile", "Account", new { id = item.Id }, null)">
                            @Html.User().Avatar(item.ProfilePicUrl, new { @class = "span2" })
                        </a>
                    </div>
                </div>
                <div>
                    @Html.ActionLink(@item.UserName, "UserProfile", "Account", new { id = item.Id }, null)
                </div>
                <div>
                    @item.Email
            </div>
        </div>
            <br />
            <hr>

        }
    </div>
</div>

CMS02/Views/Goal/_CommentView.cshtml
@model IEnumerable<CommentsViewModel>

@foreach (var item in Model)
{
    <div class="span12" style="margin-left:1px;font-size:12px;">
        <div class="span2">
            <a href="@Url.Action("UserProfile", "Account", new { id = item.UserId }, null)">
                @Html.User().Avatar(item.User.ProfilePicUrl, new { @class = "span10" })
            </a>
        </div>
        <div class="span10">
            <font color="green"> @Html.ActionLink(item.User.UserName, "UserProfile", "Account", new { id = item.UserId }, null) </font> commented "@item.CommentText"
            <div>on @item.CommentDate</div>
        </div>
    </div>
    <hr />
}

CMS02/Views/Goal/_FollowedGoals.cshtml
@model IEnumerable<CMS02_Models.Models.Goal>
<div id="divSGoals" style="height: 150px;">
    <div id="goals">
        @if (Model.Count() == 0)
        {
            <div class="alert alert-info">No events to display</div>
        }
        @foreach (var item in Model.Take(10))
        {
            <table class="table">
                <tr>
                    <td class="span1">
                        <i class="icon-star"></i>
                    </td>
                    <td class="span9">
                        @Html.ActionLink(item.GoalName/*.LimitLength(30)*/, "Index", new { id = item.GoalId }, new { @title = item.GoalName })
                    </td>
                    <td class="span2">
                        <a id="UnSupport" href="#" onclick="UnSupportGoal(@item.GoalId)" style="float:right">
                            <small>UnFollow</small>
                        </a>
                    </td>
                </tr>
            </table>

        }
    </div>
</div>
@if (Model.Count() > 10)
{
    @Html.ActionLink("See All", "GoalList", "Goal", new { filterBy = "My Followed Events" }, new { @style = "float:right;" })
}


   

CMS02/Views/Goal/_Goalslist.cshtml
@model IEnumerable<GoalListViewModel>
@{
    ViewBag.Title = "_Goalslist";
}

@foreach (var item in Model)
{ <tr>
        <td class="span1">
            <i class="icon-star"></i>
        </td>
        <td class="span9">
            <div>@Html.ActionLink(item.GoalName, "Index", "Goal", new { id = item.GoalId }, null) </div>
            <div><small>@item.StartDate- @item.EndDate</small></div>
            <div><small> Created By @Html.ActionLink(item.UserName, "UserProfile", "Account", new { id = item.UserId }, null)on @item.CreatedDate</small></div>
        </td>
        <td class="span2">
            <strong>@item.SupportsCount</strong> Supporters
        </td>
    </tr>

}


           
   