CMS02/ViewModels/ChurchUpdateViewModel.cs
using System;
using System.Collections.Generic;
using CMS02_Models.Models;

namespace CMS02.ViewModels
{
    public class ChurchUpdateViewModel
    {
        public int ChurchUpdateId { get; set; }

        public string Updatemsg { get; set; }

        public double? Status { get; set; }

        public int ChurchGoalId { get; set; }

        public DateTime UpdateDate { get; set; }

        public virtual ChurchGoal ChurchGoal { get; set; }

        public virtual ICollection<ChurchComment> ChurchComments { get; set; }

        public bool? IsSupported { get; set; }

        public int ChurchUserId { get; set; }

        public string UserId { get; set; }

        public virtual ICollection<ChurchUpdateSupport> ChurchUpdateSupports { get; set; }
    }
}

CMS02/ViewModels/ChurchViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using CMS02_Models.Models;

namespace CMS02.ViewModels
{
    public class ChurchViewModel
    {

        public int ChurchId { get; set; }

        [Required]
        public string ChurchName { get; set; }

        [Required]
        public string Description { get; set; }

        public DateTime CreatedDate { get; set; }

        //public int UserId { get; set; }

        //public int GroupUserId { get; set; }

        public virtual IEnumerable<ChurchGoalViewModel> Goals { get; set; }

        public bool IsAMember { get; set; }

        public bool RequestSent { get; set; }

        public bool InvitationSent { get; set; }

        public int NoOfMembers { get; set; }

        public bool Admin { get; set; }

        public virtual IEnumerable<Focus> Focus { get; set; }

        public virtual IEnumerable<ChurchGoalViewModel> GoalsAssignedToOthers { get; set; }

        public virtual IEnumerable<ChurchGoalViewModel> GoalsAssignedToMe { get; set; }

        //public virtual GroupUser GroupUser { get; set; }

        public IEnumerable<ApplicationUser> Users { get; set; }

    }
}

CMS02/ViewModels/CommentsViewModel.cs
using System;
using CMS02_Models.Models;

namespace CMS02.ViewModels
{
    public class CommentsViewModel
    {
        public int CommentId { get; set; }

        public string CommentText { get; set; }

        public int UpdateId { get; set; }

        public string UserId { get; set; }

        public DateTime CommentDate { get; set; }

        public ApplicationUser User { get; set; }
    }
}

CMS02/ViewModels/FocusViewModel.cs
using System.Collections.Generic;
using CMS02_Models.Models;

namespace CMS02.ViewModels
{
    public class FocusViewModel
    {
        public int FocusId { get; set; }

        public string FocusName { get; set; }

        public string Description { get; set; }

        public int ChurchId { get; set; }

        public virtual Church Church { get; set; }

        public bool IsAMember { get; set; }

        public virtual IEnumerable<ChurchGoalViewModel> ChurchGoal { get; set; }

        public virtual IEnumerable<ApplicationUser> Users { get; set; }

    }
}

CMS02/ViewModels/FollowingViewModel.cs
namespace CMS02.ViewModels
{
    public class FollowingViewModel
    {
        public string UserId { get; set; }

        public string Email { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string ProfilePicUrl { get; set; }

        public string UserName { get; set; }
    }
}

CMS02/ViewModels/MemberViewModel.cs
using CMS02_Models.Models;

namespace CMS02.ViewModels
{
    public class MemberViewModel
    {
        public int ChurchId { get; set; }

        public Church Church { get; set; }

        public string UserId { get; set; }

        public int ChurchUserId { get; set; }

        public string UserName { get; set; }

        public virtual ApplicationUser User { get; set; }

        //public IEnumerable<GroupUser> GroupUser { get; set; }

        //public IEnumerable<User> Users { get; set; }
    }
}

CMS02/ViewModels/PostUpdateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using CMS02_Models.Models;

namespace CMS02.ViewModels
{
    public class PostUpdateViewModel
    {
        public int PostUpdateId { get; set; }
        public string UpdateMessage { get; set; }
        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }

        //public DateTime PostUpdateDate { get; set; }
    }
}

CMS02/ViewModels/UpdateViewModel.cs
using System;
using System.Collections.Generic;
using CMS02_Models.Models;

namespace CMS02.ViewModels
{
    public class UpdateViewModel
    {
        public int UpdateId { get; set; }

        public string Updatemsg { get; set; }

        public double? Status { get; set; }

        public int GoalId { get; set; }

        public DateTime UpdateDate { get; set; }

        public virtual Goal Goal { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }

        public bool? IsSupported { get; set; }

        public virtual ICollection<UpdateSupport> UpdateSupports { get; set; }
    }
}

CMS02/Controllers/ChurchController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Web.Helpers;
using System.Web.Mvc;
using AutoMapper;
using CMS02.Mailers;
using CMS02.Properties;
using CMS02.ViewModels;
using CMS02_BusinessLogic;
using CMS02_BusinessLogic.Extensions;
using CMS02_Data.Infrastructure;
using CMS02_Models.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using CMS02.Models;
using CMS02_Data;
using CMS02_Service.Repository;

namespace CMS02.Controllers
{
    [Authorize]
    public class ChurchController : Controller
    {
        private readonly IChurchBusiness _groupBusiness;
        private readonly IChurchUserBusiness _groupUserBusiness;
        private readonly IMetricBusiness _metricBusiness;
        private readonly IFocusBusiness _focusBusiness;
        private readonly IChurchGoalBusiness _groupGoalBusiness;
        private readonly IUserBusiness _userBusiness;
        private readonly IChurchInvitationBusiness _groupInvitationBusiness;
        private readonly ISecurityTokenBusiness _securityTokenBusiness;
        private readonly IChurchUpdateBusiness _groupUpdateBusiness;
        private readonly IChurchCommentBusiness _groupCommentBusiness;
        private readonly IGoalStatusBusiness _goalStatusBusiness;
        public readonly IChurchRequestBusiness GroupRequestBusiness;
        private readonly IFollowUserBusiness _followUserBusiness;
        private readonly IChurchCommentUserBusiness _groupCommentUserBusiness;
        private readonly IChurchUpdateSupportBusiness _groupUpdateSupportBusiness;
        private readonly IGroupUpdateUserBusiness _groupUpdateUserBusiness;
        private readonly IAttendEventBusiness _attendEventBusiness;
        private readonly IChurchGoalRepository _groupRepository;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IPostUpdateBusiness _postUpdateBusiness;

        private IUserMailer _userMailer = new UserMailer();
        public IUserMailer UserMailer
        {
            get { return _userMailer; }
            set { _userMailer = value; }
        }

        public ChurchController(IAttendEventBusiness attendEventBusiness, IChurchBusiness groupBusiness, IChurchUserBusiness groupUserBusiness, IUserBusiness userBusiness, IMetricBusiness metricBusiness, IFocusBusiness focusBusiness, IChurchGoalBusiness groupgoalBusiness, IChurchInvitationBusiness groupInvitationBusiness, ISecurityTokenBusiness securityTokenBusiness, IChurchUpdateBusiness groupUpdateBusiness, IChurchCommentBusiness groupCommentBusiness, IGoalStatusBusiness goalStatusBusiness, IChurchRequestBusiness groupRequestBusiness, IFollowUserBusiness followUserBusiness, IChurchCommentUserBusiness groupCommentUserBusiness, IChurchUpdateSupportBusiness groupUpdateSupportBusiness, IGroupUpdateUserBusiness groupUpdateUserBusiness, IChurchGoalRepository groupRepository, IUnitOfWork unitOfWork, IPostUpdateBusiness postUpdateBusiness)
        {
            _postUpdateBusiness = postUpdateBusiness;
            _attendEventBusiness = attendEventBusiness;
            _groupBusiness = groupBusiness;
            _groupInvitationBusiness = groupInvitationBusiness;
            _userBusiness = userBusiness;
            _groupUserBusiness = groupUserBusiness;
            _metricBusiness = metricBusiness;
            _focusBusiness = focusBusiness;
            _groupGoalBusiness = groupgoalBusiness; ;
            _securityTokenBusiness = securityTokenBusiness;
            _groupUpdateBusiness = groupUpdateBusiness;
            _groupCommentBusiness = groupCommentBusiness;
            _goalStatusBusiness = goalStatusBusiness;
            GroupRequestBusiness = groupRequestBusiness;
            _followUserBusiness = followUserBusiness;
            _groupCommentUserBusiness = groupCommentUserBusiness;
            _groupUpdateSupportBusiness = groupUpdateSupportBusiness;
            _groupUpdateUserBusiness = groupUpdateUserBusiness;
            _groupRepository = groupRepository;
            _unitOfWork = unitOfWork;
        }
        //
        // GET: /Group/

        public ViewResult Index(int id)
        {
            var group = Mapper.Map<Church, ChurchViewModel>(_groupBusiness.GetGroup(id));
            group.Goals = Mapper.Map<IEnumerable<ChurchGoal>, IEnumerable<ChurchGoalViewModel>>(_groupGoalBusiness.GetGroupGoals(id));


            foreach (var item in group.Goals)
            {
                var user = _userBusiness.GetUser(item.ChurchUser.UserId);

                item.UserId = user.Id;
                item.User = user;
            }

            var assignedgroupuser = _groupUserBusiness.GetGroupUser(User.Identity.GetUserId(), id);
            if (assignedgroupuser != null)
            {
                group.GoalsAssignedToOthers = Mapper.Map<IEnumerable<ChurchGoal>, IEnumerable<ChurchGoalViewModel>>(_groupGoalBusiness.GetAssignedGoalsToOthers(assignedgroupuser.ChurchUserId));
                group.GoalsAssignedToMe = Mapper.Map<IEnumerable<ChurchGoal>, IEnumerable<ChurchGoalViewModel>>(_groupGoalBusiness.GetAssignedGoalsToMe(assignedgroupuser.ChurchUserId));
            }
            group.Focus = _focusBusiness.GetFocussOfGroup(id);

            //group.GroupUserId = GroupUserBusiness.GetGroupUserByuserId(((GpUser)(User.Identity)).UserId).GroupUserId;
            group.Users = _groupUserBusiness.GetMembersOfGroup(id);
            //if (group.GroupUser.UserId == ((GpUser)(User.Identity)).UserId)
            if (_groupUserBusiness.GetAdminId(id) == User.Identity.GetUserId())
                group.Admin = true;
            var status = 0;
            foreach (var item in group.Users)
            {
                if (item.Id == (User.Identity.GetUserId()))
                    status = 1;
            }
            if (status == 1)
                group.IsAMember = true;
            if (GroupRequestBusiness.RequestSent((User.Identity.GetUserId()), id))
                group.RequestSent = true;
            if (_groupInvitationBusiness.IsUserInvited(id, (User.Identity.GetUserId())))
                group.InvitationSent = true;
            return View("Index", group);
        }
        public ViewResult MyGroups()
        {
            var groupids = _groupUserBusiness.GetGroupAdminUsers(User.Identity.GetUserId());
            var allGroups = _groupBusiness.GetGroups(groupids);
            return View(allGroups);
        }

        public ViewResult Following()
        {
            var groupids = _groupUserBusiness.GetFollowedGroups(User.Identity.GetUserId());
            var allGroups = _groupBusiness.GetGroups(groupids);
            return View(allGroups);
        }

        public ViewResult JoinedUsers(int id)
        {
            var members = _groupUserBusiness.GetMembersOfGroup(id);
            var gmvm = new ChurchMemberViewModel() { ChurchId = id, Church = _groupBusiness.GetGroup(id), Users = members };
            return View(gmvm);
        }

        //


        public ActionResult PrintPDF(int id)
        {
            return _attendEventBusiness.PrintPdf(id);
        }
       
        // GET: /Group/Create
        public PartialViewResult CreateGroup()
        {
            var groupFormViewModel = new ChurchFormModel();
            return PartialView(groupFormViewModel);
        }

        public ViewResult ShowAllRequests(int id)
        {
            var groupRequests = GroupRequestBusiness.GetGroupRequests(id);
            var groupRequestViewModel = Mapper.Map<IEnumerable<ChurchRequest>, IEnumerable<ChurchRequestViewModel>>(groupRequests);
            ViewBag.CurrentGroupID = id;
            return View("_RequestsView", groupRequestViewModel);
        }

        public ViewResult Members(int id)
        {
            var members = _groupUserBusiness.GetMembersOfGroup(id);
            var gmvm = new ChurchMemberViewModel() { ChurchId = id, Church = _groupBusiness.GetGroup(id), Users = members };
            return View(gmvm);
        }

        public ActionResult DeleteMember(string userId, int groupId)
        {
            var membertodelete = _groupUserBusiness.GetGroupUser(userId, groupId);
            _groupUserBusiness.DeleteGroupUser(membertodelete.ChurchUserId);
            return RedirectToAction("Index", new { id = membertodelete.ChurchId });
        }

        //
        // POST: /Group/Create

        [HttpPost]
        public ActionResult CreateGroup(ChurchFormModel newGroup)
        {
            var userId = User.Identity.GetUserId();
            var group = Mapper.Map<ChurchFormModel, Church>(newGroup);
            var errors = _groupBusiness.CanAddGroup(group).ToList();
            ModelState.AddModelErrors(errors);
            if (ModelState.IsValid)
            {
                //group.UserId = ((GpUser)(User.Identity)).UserId;
                var createdGroup = _groupBusiness.CreateGroup(group, userId);
                //var createdGroup = _groupBusiness.GetGroup(newGroup.GroupName);
                //var groupAdmin = new GroupUser { GroupId = createdGroup.GroupId, UserId = ((GpUser)(User.Identity)).UserId, Admin = true };
                //GroupUserBusiness.CreateGroupUser(groupAdmin, GroupInvitationBusiness);
                var user = new ApplicationUser();
                var userName = user.UserName;
                var msg = "";
                var s = new Sms();
                msg = "Hi " + userName + ", " + "your church registration was successful and the church name is " + group.ChurchName;
                s.Send_SMs(msg, user.PhoneNumber);
                return RedirectToAction("Index", new { id = createdGroup.ChurchId });
            }
            return View("CreateGroup", newGroup);
        }

        //
        // GET: /Group/Edit
        public ActionResult EditGroup(int id)
        {
            var group = _groupBusiness.GetGroup(id);

CMS02/Views/Church/Attendees.cshtml
@using CMS02_Models.Models
@model IEnumerable<AttendEvent>
@{
    ViewBag.Title = "Event Attandee Page";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

<div class="span12">
    <div style="float:left;margin-left:25px;">
    </div>

    @*<div style="float:right;">
        @Html.ActionLink("Back To Event", "GroupGoal", "Church", new { id = Model.ChurchGoalId }, new { @class = "btn btn-info", style = "float:right" })
    </div>*@
</div>

<div class="span12">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChurchGoals.GoalName)
            </th>
        </tr>
          
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ChurchGoals.GoalName)
                </td>
            </tr>
            @Html.ActionLink("Print", "PrintPDF", new { id = item.ChurchGoalId })
        }
    </table>
</div>

CMS02/Views/Church/ChurchUpdate.cshtml
@using Microsoft.AspNet.Identity
@model ChurchGoalViewModel
@{
    ViewBag.Title = Model.GoalName;
    ViewContext.Controller.ViewBag.IncludeJqplot = true;
    Layout = "~/Views/Shared/_GoalLayout.cshtml";
}
@Html.Hidden("GroupId", @Model.ChurchId)
@Html.Hidden("GroupUpdates", Model.Updates.Count())
@{
    ViewBag.Title = "ChurchUpdate";
}

<h2>ChurchUpdate</h2>

<!--Update section -->
<div class="span6 well" style="margin-left: 0px;">
    @if (User.Identity.GetUserId() == Model.UserId || User.Identity.GetUserId() == Model.AssignedUserId)
    {
        <table class="table" id="UpdatePostContent">
            <thead>
                <tr>
                    <th>
                        <h5>
                            Post Your Update
                        </h5>
                    </th>
                </tr>
            </thead>
            <tr>
                <td>
                    @Html.TextArea("GroupUpdate", "", new { @class = "span12", placeholder = "Add an update for this event" })
                </td>
            </tr>
            <tr><td><div id="UpdateGroupValidation"></div></td></tr>
            @if (Model.Metric != null)
            {
                <tr>
                    <td class="span8">
                        <div class="input-append">
                            @if (Model.Metric != null)
                            {
                                <input type="text" id="Status" onfocus="clearStatusError()" class="span8" placeholder="Add new satus of this update" />

                            }
                            @if (Model.Metric != null && Model.Target != null)
                            { <span class="add-on">/@Model.Target @Model.Metric.Type</span>}
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div id="statusError">
                        </div>
                    </td>
                </tr>
            }
        </table>
    }
    <div id="divgroupupdate" style="margin: 0px;">
        @{ Html.RenderAction("DisplayUpdates", "Church", Model.ChurchGoalId); }
    </div>
    <div id="divInviteLayer" class="jqmWindow">
        <div id="handle" style="float: right">
            <a href="#" class="jqmClose">Close</a>
        </div>
        <div id="DivInviteContent">
        </div>
    </div>
</div>
<!--Update Section Ends here-->
<script type="text/javascript">
    function saveGroupUpdate(target, metric) {

        var update = 'Please Enter Update';


        var gid = $('#GoalId').val();
        var currUpdte = $('#GroupUpdate').val();
        var currStatus = $('#Status').val();
        var groupId = $('#ChurchId').val();


        if (currUpdte === '') {
            $('#UpdateGroupValidation').html('<label class="field-validation-error">Please Enter Update</label>');

        }
        else {
            $('#UpdateGroupValidation').html('');
            var postData = { 'ChurchGoalId': gid, 'Updatemsg': currUpdte, 'status': currStatus, 'ChurchId': groupId };
            var url = '/Church/SaveUpdate';
            var numericCheck = DecimalValidate(currStatus);
            if ((currStatus === '') || (currStatus !== '' && numericCheck)) {
                $.post(url, postData, function (response) {
                    $("#divgroupupdate").html(response);
                    $("#GroupUpdate").val('');
                    $("#Status").val('');
                });
            }
            else {
                $("#statusError").html('<label style="color:red;">Enter a valid status.</label>');
            }
        }
    }

</script>

CMS02/Views/Church/CreateGroup.cshtml
@{
    ViewBag.Title = "Create Church";
}
@model ChurchFormModel
<div class ="span5 ">
    @using (Html.BeginForm())
    { 
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <table>
            <tr>               
                <td>
                    @Html.TextBoxFor(m => m.ChurchName, new { @class="span5",id = "InputGroup",style ="display:block;",placeholder = "Church Name" }) @Html.ValidationMessageFor(m => m.ChurchName)                
                </td>                
            </tr>
            <tr>               
                <td>
                    @Html.TextAreaFor(m => m.Description, new { @class = "span5", id = "InputGroupDesc", placeholder = "Church Description", style = "display:block;" }) @Html.ValidationMessageFor(m => m.Description)                
                </td>
                
            </tr>
            <tr>
                <td>
                <input type="submit" class="btn btn-primary pull-left" value="Create" id="CreateGroup" style="margin-right:5px;" /> 
                 <input type="button" class="btn" value="Cancel" id="cancel" style="margin-right:5px;" onclick="window.location.href = '@Url.Action("Index", "Home")'" /> 
        
                </td>
            </tr>
             </table>
           
                    
    }
       
   
</div>
@*<style type="text/css">
            table
            {
                border-collapse: collapse;
                
            }
            table,td
            {
               @* border: 1px solid black;
            }
            input
            {
                border-radius:5px;
            }
        </style>
*@

CMS02/Views/Church/CreateGroupView.cshtml
@{
    ViewBag.Title = "Create ChurchView";
}

<h2>CreateChurchView</h2>

@{
    ViewBag.Title = "Create";
}

<h2>Create Church</h2>

@{
    ViewBag.Title = "Create Church";
}
@model ChurchFormModel
<div class="span5 ">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <table>
            <tr>
                <td>
                    @Html.TextBoxFor(m => m.ChurchName, new { @class = "span5", id = "InputGroup", style = "display:block;", placeholder = "Church Name" }) @Html.ValidationMessageFor(m => m.ChurchName)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.TextAreaFor(m => m.Description, new { @class = "span5", id = "InputGroupDesc", placeholder = "Church Description", style = "display:block;" }) @Html.ValidationMessageFor(m => m.Description)
                </td>

            </tr>
            <tr>
                <td>
                    <input type="submit" class="btn btn-primary pull-left" value="Create" id="CreateGroup" style="margin-right:5px;" />
                    <input type="button" class="btn" value="Cancel" id="cancel" style="margin-right:5px;" onclick="window.location.href = '@Url.Action("Index", "Home")'" />

                </td>
            </tr>
        </table>


    }


</div>

CMS02/Views/Church/DeleteFocus.cshtml
@model CMS02_Models.Models.Focus

@{
    ViewBag.Title = "Delete Group";
}

<div class ="alert alert-block alert-error fade in">
<strong>Delete Focus</strong>
<br />
     Are you sure you want to delete this?
     <br />
     <br />
   
<table>
            <tr>
                <td >
                    @Html.DisplayNameFor(model => model.FocusName)
                </td>
                <td >
                    @Html.DisplayFor(model => model.FocusName)
                   
                </td>
            </tr>
            <tr>
                <td >
                    @Html.DisplayNameFor(model => model.Description)
                </td>
                <td >
                    @Html.DisplayFor(model => model.Description)
                </td>
            </tr>
            </table>
            <br />
              <p>
            

        @using (Html.BeginForm())
{
            @Html.AntiForgeryToken()
    <p>
      

             <button class="btn btn-danger" type="submit"  value="Submit"> Delete</button>
             <button class="btn" value="Cancel"  type ="reset" onclick="window.location.href = '@Url.Action("Index", "Church", new { id = Model.ChurchId})'">
        Cancel</button>
        
    </p>
      
     
 
 

}
 
</div>

CMS02/Views/Church/Following.cshtml
@model IEnumerable<CMS02_Models.Models.Church>

@{
    ViewBag.Title = "MyGroups";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}


              @if (Model.Count() == 0)
{
   <div class ="alert alert-info">
   No results To Display
   </div>
}

               
                   @foreach (var item in Model)
                   { 
                        <div class="alert users span2">
                      <h4> @item.ChurchName</h4>
   
                        
                @Html.ActionLink(@Html.Action("NoOfUsers", new { id = @item.ChurchId }) + " Members", "JoinedUsers", new { id = @item.ChurchId }, null)
                     </div>
                   }
                 
                  

CMS02/Views/Church/InviteUser.cshtml
@model CMS02_Models.Models.ApplicationUser
@Model.UserName has been invited to join the Church.

CMS02/Views/Church/JoinedUsers.cshtml
@model ChurchMemberViewModel
@{
    ViewBag.Title = "Members";
}
<h3>
    @Html.ActionLink(@Model.Church.ChurchName, "Index", new { id = @Model.ChurchId })
</h3>
<div class="subnav">
    <ul class="nav nav-pills">
        <li class="">@Html.ActionLink(@Html.Action("NoOfUsers", new { id = @Model.ChurchId }) + " Members", "JoinedUsers", new { id = @Model.ChurchId }, null)
          
    </ul>
</div>
<br />
<br />
<div class="span12" >
    @foreach (var item in Model.Users)
    {
        <div class="alert alert-info span3">
            <div>
                @Html.ActionLink(@item.UserName, "UserProfile", "Account", new { id = item.Id }, null)
            </div>
            <div>@item.Email
            </div>
        </div>
    }
</div>

CMS02/Views/Church/Members.cshtml
@model ChurchMemberViewModel
@{
    ViewBag.Title = "Members";
}
<h3>
    @Html.ActionLink(@Model.Church.ChurchName, "Index", new { id = @Model.ChurchId })
</h3>
@Html.Partial("Header")
<br />
<br />
<div class="well span4" id="memberlist" style="height: 320px">
        <h4>
            MEMBERS</h4>
         @foreach (var item in Model.Users)
            {
                <div >
                <div style="position:relative">
                <div>
                    <a href="@Url.Action("UserProfile", "Account", new { id = item.Id }, null)" >
                        @Html.User().Avatar(item.ProfilePicUrl, new { @class = "span1" })
                    </a></div>
                    </div>
                  
                        <div>
                            @Html.ActionLink(@item.UserName, "UserProfile", "Account", new { id = item.Id }, null)
                        </div>
                    
                </div>
                  <br />
                <hr >
              
            }
    </div>

CMS02/Views/Church/_DeleteGroup.cshtml
@model CMS02_Models.Models.Church

@{
    ViewBag.Title = "Delete Church";
}

<div class ="alert alert-block alert-error fade in">
<strong>Delete Church</strong>
<br />
     Are you sure you want to delete this?
     <br />
     <br />
   
<table>
            <tr>
                <td >
                    @Html.DisplayNameFor(model => model.ChurchName)
                </td>
                <td >
                    @Html.DisplayFor(model => model.ChurchName)
                   
                </td>
            </tr>
            <tr>
                <td >
                    @Html.DisplayNameFor(model => model.Description)
                </td>
                <td >
                    @Html.DisplayFor(model => model.Description)
                </td>
            </tr>
            </table>
            <br />
              <p>
            

        @using (Html.BeginForm())
{
            @Html.AntiForgeryToken()
    <p>
      

             <button class="btn btn-danger" type="submit"  value="Submit"  onclick ="Delete(@Model.ChurchId)"> Delete</button>
             <button class="btn" value="Cancel"  type ="reset" onclick="window.location.href = '@Url.Action("Index", "Church", new { id = Model.ChurchId })'">
        Cancel</button>
        
    </p>
      
     
 
 

}
 
</div>